# Source: https://github.com/DavidAnson/markdownlint/blob/b2305efafb034b1f328845aec9928b5363ffd646/style/cirosantilli.json
comment: Rules for the style guide at https://www.cirosantilli.com/markdown-style-guide/,

default: true
MD003:
  style: atx
MD004:
  style: dash
MD007:
  indent: 4
MD030:
  ul_multi: 3
  ol_multi: 2
MD033: false
MD035:
  style: ---

# Fixes (these were missing in the source, likely mistakenly):
emphasis-style:
  style: asterisk

# Changes (local adjustments specific to this project):
first-line-heading: false # (in Lume, a "missing" title is usually just inherited from parent data)
